### ISSUE TITLE
The frontend master branch is no longer running any tests in CircleCI, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-front#136]

**Comment by LinuxBozo** [comment]
Looks like it is to me..  https://circleci.com/gh/WebJamApps/web-jam-front/118 . See `npm test` section.

**Comment by LinuxBozo** [comment]
And again.. https://circleci.com/gh/WebJamApps/web-jam-front/123.  Perhaps you were confused by merging master -> dev instead of dev -> master?

When you see this thing in github that asks you to compare and do a PR with master, ignore it.
<img width="993" alt="screen shot 2017-04-04 at 9 52 19 pm" src="https://cloud.githubusercontent.com/assets/723420/24686324/2545a3fa-1981-11e7-94b4-3ece037f4a3f.png">
